

- name: criando os usuarios padroes para todas as maquinas
  user:
   name: "{{item.nome}}"
   password: "{{item.senha}}"
   state: "{{item.estado}}"
   home: "{{item.casa}}"
  with_items:
    - { nome: luciano, senha: '$1$TkhyX.Mt$cIZ.9AfCTSBi6b4TdLEnD', estado: present, casa: /srv/luciano }
    - { nome: devops, senha:  '$1$TkhyX.Mt$cIZ.9AfCTSBi6b4TdLEnD', estado: present, casa: /srv/devops }
    - { nome: developer, senha: '$1$TkhyX.Mt$cIZ.9AfCTSBi6b4TdLEnD', estado: present, casa: /srv/developer }
