- name: Instala Rundeck no CentOS
  hosts: automation
  tasks:
   - name: atualiza repositorio do rundeck
     yum:
      name: http://repo.rundeck.org/latest.rpm
      state: present

   - name: instalando o java e o rundeck
     package:
      name: "{{item}}"
     with_items:
       - java
       - rundeck


